server:
    servlet:
        context-path: /emailservice

spring:
    application:
        name: emailservice
    profiles:
        active: server
    cloud.discovery.client.composite-indicator.enabled: false
    jpa.properties:
        hibernate:
            default_schema: ${db.postgreSql.schema}
            dialect: org.hibernate.dialect.PostgreSQLDialect

db:
    postgreSql:
        schema: SCH_EMAILSERVICE
        dialect: org.hibernate.dialect.PostgreSQLDialect
