spring:
    application:
        name: emailservice
    profiles:
        active: server
    cloud.discovery.client.composite-indicator.enabled: false
    jpa.database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    h2.console:
        enabled: true
        settings.web-allow-others: true

email:
    sendgrid:
        apiKey: ${SENDGRID_APIKEY}
        verified.emailaddress.from: ${SENDGRID_VERIFIED_EMAILADDRESS}
    mailgun:
        apiKey: ${MAILGUN_APIKEY}
        verified.emailaddress.to: ${MAILGUN_VERIFIED_EMAILADDRESS}

application.url: http://emailservice-app.azurewebsites.net/api

management:
    endpoint.health.show-details: always
    endpoints.web:
        base-path: /
        exposure.include: info, health
