spring:
    application:
        name: emailservice
    profiles:
        active: server
    cloud.discovery.client.composite-indicator.enabled: false
    jpa.database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: username
        password: password
    h2.console.enabled: true

email:
    sendgrid:
        apiKey: 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
        verified.emailaddress.from: eljakim.lindenburg@student.pxl.be

application.url: https://webhook.site/7d2a0c9b-0778-48f7-968d-a16e9d1ae73f

management:
    endpoint.health.show-details: always
    endpoints.web:
        base-path: /
        exposure.include: info, health
