server:
    servlet:
        context-path: /emailservice

spring:
    application:
        name: emailservice
    profiles:
        active: server
    cloud.discovery.client.composite-indicator.enabled: false
    jpa.properties:
        hibernate:
            default_schema: ${db.postgreSql.schema}
            dialect: org.hibernate.dialect.PostgreSQLDialect

db:
    postgreSql:
        schema: SCH_EMAILSERVICE
        dialect: org.hibernate.dialect.PostgreSQLDialect

axon:
    metrics.auto-configuration.enabled: true
    axonserver.servers: axonserver01${service.appendix}:8124,axonserver02${service.appendix}:8124,axonserver03${service.appendix}:8124
    vdab:
        resource.tokens.prefix: management
        db.schema: ${db.postgreSql.schema}
        contextnames:
            - emailservice
        contexts:
            documentbeheer:
                primary: true
        sagastore.enabled: true
