DROP TABLE IF EXISTS EMAIL_QM;

CREATE TABLE EMAIL_QM (
    ID                          INT AUTO_INCREMENT  PRIMARY KEY,
    CORRELATIE_UUID             UUID NOT NULL,
    PROVIDER                    VARCHAR2(50 CHAR) NOT NULL,
    STATUS                      VARCHAR2(50 CHAR) NOT NULL,
    CREATIE_TIMESTAMP           TIMESTAMP NOT NULL,
    LAATSTE_UPDATE_TIMESTAMP    TIMESTAMP NOT NULL,
    AFZENDER                    VARCHAR2(255 CHAR) NOT NULL,
    GEADRESSEERDE_EMAIL         VARCHAR2(255 CHAR) NOT NULL,
    GEADRESSEERDE_NAAM          VARCHAR2(255 CHAR) NOT NULL,
    INHOUD                      CLOB NOT NULL,
    ONDERWERP                   VARCHAR2(255 CHAR) NOT NULL,
    primary key(ID)
);

INSERT INTO EMAIL_QM (CORRELATIE_UUID, PROVIDER, STATUS, CREATIE_TIMESTAMP, LAATSTE_UPDATE_TIMESTAMP, AFZENDER, GEADRESSEERDE_EMAIL, GEADRESSEERDE_NAAM, INHOUD, ONDERWERP) VALUES
  ('aa35cc12-e53f-4ecc-9415-692443de5413', 'SENDGRID', 'INITIEEL', '2017-02-03T10:37:30.00Z', '2017-02-03T10:37:30.00Z', 'eljakim.lindenburg@student.pxl.be', 'eljakim.l@gmail.com', 'Eljakim Lindenburg', 'testInhoud', 'testOnderwerp');
